@CRUD_APP1_HostAddress = http://localhost:5136

### Create a product
POST {{CRUD_APP1_HostAddress}}/Product
Content-Type: application/json

{
    "id": 1,
    "name": "Keyboard",
    "price": 1500,
    "quantity": 5
}

### Get all products
GET {{CRUD_APP1_HostAddress}}/Product
Accept: application/json

### Get product by ID
GET {{CRUD_APP1_HostAddress}}/Product/2
Accept: application/json

###
PUT {{CRUD_APP1_HostAddress}}/Product/1
Content-Type: application/json

{
    "name": "Gaming Keyboard",
    "price": 2500,
    "quantity": 10
}

###
DELETE {{CRUD_APP1_HostAddress}}/Product/1